config/routes.rb
Rails.application.routes.draw do


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root to: 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Routes for Google authentication
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'users/:user_id/itineraries/selected_city', to: 'itineraries#selected_city'

  resources :events
  resources :itineraries

  resources :destinations do
    resources :events
  end

  post '/destinations/:id', to: 'destinations#chosen_destination'

  resources :users do
    resources :itineraries, only: [:index]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    belongs_to :user
    belongs_to :destination
    belongs_to :event

    validates :name, :destination_id, :event_id, presence: { message: "must be populated" }, on: :create
    validates_uniqueness_of :user_id, :scope => [:destination_id, :event_id], :message=>"has previously created identical itinerary", on: :create

    validate :event_in_destination?, on: :create
    validate :event_is_upcoming?, on: :create

    def event_in_destination?
        if !destination.events.include?(event)
            errors.add :event, 'selected does not take place in Destination selected'
        end
    end    

    def event_is_upcoming?
        if !Event.upcoming.include?(event)
            errors.add :event, 'has already occurred'
        end
    end 

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
    before_action :redirect_if_not_logged_in, :redirect_if_admin?
    before_action :set_itinerary, only: [:update, :destroy]
    before_action :authorized_user_itinerary, only: [:show, :edit]

 
    def new
        @itinerary = Itinerary.new
    end

    def create
        @itinerary = current_user.itineraries.build(itinerary_params)
        if date_and_time_conflict?
            flash[:message] = "There is a date and time conflict with previously scheduled event in your Itinerary."
            redirect_to new_itinerary_path            
        else
            if @itinerary.save
                flash[:success] = "Successfully created Itinerary."
                redirect_to itinerary_path(@itinerary)
            else
                render :new
            end            
        end
    end

    def show
    end


    def index  
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])

            if @user == current_user
                @upcoming_events_sorted = current_user.events.upcoming.sorted_by_event_date
            else
                flash[:message] = "Not authorized to see other user's itineraries"
                redirect_to root_path
            end
        else
            flash[:message] = "Not authorized to itineraries of other users"
            redirect_to root_path 
        end   
    end


    def edit 
    end

    def update
        @itinerary.update(itinerary_params)
        flash[:success] = "Successfully updated Itinerary."
        redirect_to itinerary_path(@itinerary)
    end


    def destroy
        @itinerary.destroy
        flash[:success] = "Successfully removed Itinerary."
        redirect_to user_itineraries_path(current_user)
    end


    def selected_city
        @destination = Destination.find_by(id: params[:itinerary][:destination_id])
        @upcoming_destination_events_sorted = current_user.events.upcoming.sorted_by_event_date.where(destination_id: params[:itinerary][:destination_id])
    end


    private
    def itinerary_params
        params.require(:itinerary).permit(:name, :destination_id, :event_id, :notes)
    end  

    def date_and_time_conflict?
        selected_event = Event.find_by(id: params[:itinerary][:event_id])
        current_user.events.any? {|e| e.event_date.to_s == selected_event.event_date.to_s}
    end

    def set_itinerary
        @itinerary = Itinerary.find_by(id: params[:id])
    end

    def authorized_user_itinerary
        itinerary = Itinerary.find_by(id: params[:id])
        if current_user.itineraries.include?(itinerary)
            @itinerary = itinerary
        else
            flash[:message] = "Not authorized to see other user's itineraries"
            redirect_to root_path
        end 
    end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_form.html.erb
<% if params[:action] == "new" %>
    <p id="upcoming_events_message">
        <%="There are #{Event.upcoming.count} upcoming events! Choose your destination and add your selected event here!"%>
    </p>
<% end %>

<div class="itinerary_form">
    <%= form_for @itinerary do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %><br><br>

        <%= f.label :destination %>
        <%= f.collection_select :destination_id, Destination.all, :id, :city %><br><br>

        <%= f.label :event %>
        <%= f.grouped_collection_select :event_id, Destination.order(:city), :events, :city, :id, :description %><br><br>    

        <%= f.label :notes %>
        <%= f.text_area :notes %><br><br>

        <%= f.submit %>

    <% end %>
</div>

app/views/itineraries/_itinerary.html.erb
<p><%=user_itinerary.name%></p>
<p><%=user_itinerary.destination.city%></p>
<p><%=user_itinerary.event.description%></p>
<% if user_itinerary.event.ticket_site.present?%>
    <p><%= link_to "Ticket Site", user_itinerary.event.ticket_site, target: :_blank %></p>   
<% end %> 
<p><%=user_itinerary.event.event_date.strftime("%m/%d/%Y")%></p> 
<p><%=user_itinerary.event.event_date.strftime("at %I:%M%p")%></p>
<p><%=user_itinerary.notes%></h1>
<p><%= link_to "Edit", edit_itinerary_path(user_itinerary) %></p> | <p><%= link_to "Delete Itinerary", itinerary_path(user_itinerary), :method => :delete %><p>

app/views/itineraries/edit.html.erb
<h1>Edit Itinerary</h1>

<%= form_tag itinerary_path(@itinerary), method: "put" do %>
    <%= render 'form' %>
  <% end %>

app/views/itineraries/index.html.erb
<h1> All Itineraries </h1>

<%= render 'layouts/flash' %>

<div id="itinerary_destination_filter">
    <h2> Filter by Destination </h2>

    <%= form_tag(controller: "itineraries", action: "selected_city", method: "post") do %>
        <%= collection_select :itinerary, :destination_id, current_user.destinations.uniq, :id, :city, {include_blank: 'Select a Destination'} %><br><br>
        <div><%= submit_tag 'Go' %></div>
    <% end %>
</div><br><br>

<% @upcoming_events_sorted.each do |upcoming_event| %>

    <div class="your_itineraries">
        <%= render partial: "itinerary", locals: {user_itinerary: upcoming_event.itineraries.find_by(user_id: current_user.id)} %>
    </div>  
    <br><br>  

<% end %>

app/views/itineraries/new.html.erb
<h1>New Itinerary</h1>

<%= render 'layouts/flash' %>

<%= render partial: "layouts/errors", locals: {object: @itinerary} %>

<%= form_tag itineraries_path, method: "create" do %>
    <%= render 'form' %>
<% end %>

app/views/itineraries/selected_city.html.erb
<h1><%= "All Itineraries For #{@destination.city}" %></h1>


<% @upcoming_destination_events_sorted.each do |upcoming_destination_event| %>

    <div class="your_itineraries">
        <%= render partial: "itinerary", locals: {user_itinerary: upcoming_destination_event.itineraries.find_by(user_id: current_user.id)} %>
    </div>  

    <br><br>  
<% end %>

app/views/itineraries/show.html.erb
<h1> Created Itinerary </h1>

<%= render 'layouts/flash' %>

<div class="created_itinerary">

    <%= render partial: "itinerary", locals: {user_itinerary: @itinerary} %>

</div>