config/routes.rb
Rails.application.routes.draw do


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root to: 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Routes for Google authentication
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'users/:user_id/itineraries/selected_city', to: 'itineraries#selected_city'

  resources :events
  resources :itineraries

  resources :destinations do
    resources :events
  end

  post '/destinations/:id', to: 'destinations#chosen_destination'

  resources :users do
    resources :itineraries, only: [:index]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :destination
    has_many :itineraries
    has_many :users, through: :itineraries

    scope :upcoming, -> {where("events.event_date > ?", DateTime.current())}
    scope :sorted_by_event_date, -> {order(event_date: :asc)}

    validates :description, :destination_id, :event_date, presence: { message: "must be populated" }, on: :create
    validates_length_of :ticket_site, minimum: 5, maximum: 200, allow_blank: true

    validates_uniqueness_of :description, :scope => [:destination_id, :event_date], :message=>"matches event occurring in same destination and on the same date", on: :create

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :redirect_if_not_logged_in, :redirect_if_not_admin?
    before_action :set_destination
    before_action :destination_event, only: [:show, :edit]
    before_action :set_event, only: [:update, :destroy]

    def new

        if @destination
            @event = @destination.events.build
        else   
            flash[:message] = "Please select destination to associate event with"
            redirect_to destinations_path   
        end
    end 


    def create

        if params[:destination_id]

            if @destination
                @event = @destination.events.build(event_params)
 
                if @event.save
                    flash[:success] = "Successfully created event"
                    redirect_to destination_events_path(@destination)
                else
                    render :new
                end
            else
                flash[:message] = "Destination does not exist"
                redirect_to destination_events_path                    
            end
        else
            redirect_to destination_events_path         
        end
    end


    def index 
        if params[:destination_id]

            if @destination
                @events = @destination.events.sort_by { |e| e.event_date}
            else
                flash[:message] = "Destination not found"
                redirect_to root_path
            end
        else
            redirect_to destination_events_path  
        end
    end


    def show
    end


    def edit 
    end

    def update
        if params[:destination_id]

            if @destination
                if @event
                    @event.update(event_params)
                    flash[:success] = "Successfully updated event"
                    redirect_to destination_event_path(@destination, @event)      
                else
                    flash[:message] = "Event does not exist"
                    redirect_to destinations_path   
                end      
            else     
                flash[:message] = "Destination does not exist"
                redirect_to destination_events_path 
            end                               
        else
            redirect_to destination_events_path 
        end

    end


    def destroy
        if params[:destination_id]        

            if @destination
                if @event   
                    @event.destroy
                    flash[:success] = "Successfully removed event"
                    redirect_to destination_events_path(@destination, @event)
                else
                    flash[:message] = "Event does not exist"
                    redirect_to destinations_path   
                end      
            else     
                flash[:message] = "Destination does not exist"
                redirect_to destinations_path  
            end                    
        else
            redirect_to destinations_path 
        end
    end


    private
    def event_params
        params.require(:event).permit(:description, :destination_id, :ticket_site, :event_date)
    end    

    def set_destination
        @destination = Destination.find_by_id(params[:destination_id])
    end

    def set_event
        @event = @destination.events.find_by_id(params[:id])  
    end    

    def destination_event
        if params[:destination_id]
            if @destination
                @event = @destination.events.find_by_id(params[:id])
                if !@event
                    flash[:message] = "Event does not exist"
                    redirect_to destination_events_path 
                end                    
            else
                flash[:message] = "Destination does not exist"
                redirect_to destination_events_path 
            end
        else
            redirect_to destination_events_path   
        end
    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<p><%=destination_event.description %></p>
<% if destination_event.ticket_site.present?%>
    <p><%=link_to "Ticket Site", destination_event.ticket_site, target: :_blank %></p>
<% end %> 
<p><%=destination_event.event_date.strftime("%m/%d/%Y")%></p> 
<p><%=destination_event.event_date.strftime("at %I:%M%p")%></p>  
<p><%= link_to "Edit Event", edit_destination_event_path(destination, destination_event) %></p>
<p><%= link_to "Delete Event", destination_event_path(destination, destination_event), :method => :delete %></p>

app/views/events/_form.html.erb
<div class="event_form">
    <%= form_for [@destination, @event] do |f| %>

        <%= f.label :description %>
        <%= f.text_field :description %><br><br>
    
        <%= f.label :ticket_site %>
        <%= f.text_field :ticket_site %><br><br>
    
        <%= f.label :event_date %>
        <%= f.datetime_field :event_date, :value => DateTime.now.strftime("%m/%d/%Y %I:%M%p") %><br><br>
    
        <%= f.submit %>

    <% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_tag destination_event_path(@destination, @event), method: "put" do %>
    <%= render 'form' %>
  <% end %>

app/views/events/index.html.erb
<%= render 'layouts/flash' %>

<h1> <%="#{@destination.city} Events" %></h1><br><br>

<div class="destination_links">
    <%= link_to "Add Event", new_destination_event_path %><br><br>
    <%= link_to "Back to Destination Page", destination_path(@destination) %><br>  
</div><br><br>

<% @events.each do |e| %>
    <div class="destination_event">

        <%= render partial: "event", locals: {destination: @destination, destination_event: e} %>

    </div><br><br>
<% end %>

app/views/events/new.html.erb
<h1><%="Add New Event for #{@destination.city}" %></h1>

<%= render partial: "layouts/errors", locals: {object: @event} %>

<%= form_tag destination_events_path, method: "create" do %>
    <%= render 'form' %>
<% end %>

app/views/events/show.html.erb
<%= render 'layouts/flash' %>

<h1><%= @destination.city %></h1>

<div class="destination_event">

    <%= render partial: "event", locals: {destination: @destination, destination_event: @event} %>

</div>