config/routes.rb
Rails.application.routes.draw do


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root to: 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Routes for Google authentication
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'users/:user_id/itineraries/selected_city', to: 'itineraries#selected_city'

  resources :events
  resources :itineraries

  resources :destinations do
    resources :events
  end

  post '/destinations/:id', to: 'destinations#chosen_destination'

  resources :users do
    resources :itineraries, only: [:index]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :itineraries
    has_many :events
    has_many :users, through: :itineraries

    validates_uniqueness_of :city, :case_sensitive => false, :message => "already exists in database", on: :create

    @city_regex = /[^,]*,[^,]*/
    validates :city, 
        :format => { :with => @city_regex, :message => "Invalid city format. Must be 'city, state' format" }

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :redirect_if_not_logged_in, :redirect_if_not_admin?
    before_action :set_destination, only: [:show, :edit, :update, :destroy]

    def new
        @destination = Destination.new
    end

    def create
        @destination = Destination.new(destination_params)
        if @destination.save
            flash[:success] = "You have successfully added #{@destination.city} as a destination!"
            redirect_to destination_path(@destination)
        else
            render :new
        end        
    end

    def index
        @destinations = Destination.all
    end

    def show
    end


    def edit 
    end

    def update
        @destination.update(destination_params)
        flash[:success] = "You have successfully edited destination!"
        redirect_to destination_path(@destination)
    end


    def destroy
        @destination.destroy
        flash[:success] = "You have successfully deleted destination!"
        redirect_to destinations_path(@destination)
    end


    def chosen_destination
        @destination = Destination.find_by(city: params[:city])
        if @destination
            redirect_to destination_path(@destination)
        else
            flash[:message] = "Searched destination not found. Please try again."
            redirect_to destinations_path
        end
    end

    private
    def destination_params
        params.require(:destination).permit(:city)
    end    

    def set_destination
        @destination = Destination.find_by_id(params[:id])
    end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<div class="destination_form">
    <%= form_for @destination do |f| %>

        <%= f.label :city %>
        <%= f.text_field :city %><br><br>

        <%= f.submit %>

    <% end %>
</div>

app/views/destinations/edit.html.erb
<h1>Edit Destination</h1>

<%= form_tag destination_path(@destination), method: "put" do %>
    <%= render 'form' %>
  <% end %>

app/views/destinations/index.html.erb
<h1> All Destinations </h1>

<%= render 'layouts/flash' %>

<%= form_tag("/destinations/:id", method: "post") do %>
    <%= label_tag(:city, "Search for:") %>
    <%= text_field_tag(:city) %>
    <%= submit_tag("Search") %>
<% end %>


<% @destinations.each do |d| %>
    <div class="all_destinations">
        <%= link_to "#{d.city}", destination_events_path(d) %><br>  
    </div>  
    <br><br>  
<% end %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render partial: "layouts/errors", locals: {object: @destination} %>

<%= form_tag destinations_path, method: "create" do %>
    <%= render 'form' %>
<% end %>

app/views/destinations/show.html.erb
<%= render 'layouts/flash' %>

<h1><%= @destination.city %></h1>

<div class="destination_links">
    <p><%= link_to "Edit Destination", edit_destination_path(@destination) %></p>
    <p><%= link_to "Delete Destination", destination_path(@destination), :method => :delete %></p>
</div>