config/routes.rb
Rails.application.routes.draw do


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root to: 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Routes for Google authentication
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'users/:user_id/itineraries/selected_city', to: 'itineraries#selected_city'

  resources :events
  resources :itineraries

  resources :destinations do
    resources :events
  end

  post '/destinations/:id', to: 'destinations#chosen_destination'

  resources :users do
    resources :itineraries, only: [:index]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this object from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:message] %>
    <div class="flash-message">
        <%= flash[:message]%>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="flash-success">
        <%= flash[:success]%>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyItinerary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">


  </head>

  <body>
    <div class= "navbar">
      <%= link_to "Home", root_path %>
      <% if logged_in? %>
        <% if is_admin? %>
          <%= link_to "New Destination", new_destination_path %>
          <%= link_to "All Destinations", destinations_path %>
        <% elsif %>  
          <%= link_to "Add Itinerary", new_itinerary_path %>
          <%= link_to "Your Itineraries", user_itineraries_path(current_user) %>
        <% end %>  
        <%= link_to "Logout", logout_path, method:"delete" %>
      <% else %>
          <%= link_to "Sign Up", signup_path %>
          <%= link_to "Log In", login_path %>
      <% end %>
    </div>
    <%= yield %>
  </nav>
</html>